import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import HomeHeader from "~/components/homeHeader";
// import { api } from "~/utils/api";
import Image from "next/image";
import NavigationBar from "~/components/navigationBara";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Inter College Coding Competition</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavigationBar />
        <section>
          {/* BACKGROUND IMAGE */}
          <div style={{ width: "100%", height: "100vh", position: "absolute" }}>
            <Image src={"/home_bg.jpg"} alt="background image" fill />
          </div>

          {/* HOME HEADER COMPONENTS: Title and Image */}
          <div className="relative mx-auto max-w-screen-xl px-4 py-32 sm:flex sm:flex-col sm:items-center sm:px-6 lg:flex-row lg:items-start">
            <div className="mt-20 flex justify-center px-7">
              <HomeHeader />
            </div>
            <div className="mt-20 flex justify-center px-7">
              <Image
                src={"/home_bg_1.png"}
                alt="Coding Image"
                width={500}
                height={500}
              />
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
